# Generated by Django 5.0.1 on 2024-04-24 21:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acontecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField()),
                ('encabezado', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('enlace', models.URLField()),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True)),
                ('foto', models.FileField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Acontecimientos',
            },
        ),
        migrations.CreateModel(
            name='Centros_y_Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', ckeditor.fields.RichTextField()),
                ('dirección', models.CharField(max_length=500)),
                ('télefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Centros y Empresas',
            },
        ),
        migrations.CreateModel(
            name='Efemerides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField()),
                ('encabezado', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Efemérides',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField()),
                ('encabezado', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('enlace', models.URLField()),
                ('hora', models.TimeField()),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True)),
                ('foto', models.FileField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Historia_de_la_Institución',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='images/')),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Historia de la Institución',
            },
        ),
        migrations.CreateModel(
            name='Iconos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('S_Efemerides', 'Sección Efemerides'), ('S_BannerPpal', 'Sección Banner Principal'), ('S_Eventos', 'Sección Eventos'), ('S_Revista', 'Sección Revista')], max_length=50)),
                ('foto', models.FileField(upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Iconos',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('tipo', models.CharField(max_length=100)),
                ('enlace', models.URLField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='images/')),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Multimedias',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('link_podcast', models.URLField()),
                ('foto', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Premio_Nacional_de_Música',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('año', models.DateField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('bibliografía', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='images/')),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Premio Nacional de Música',
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('imagen_portada', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', ckeditor.fields.RichTextField()),
                ('foto', models.FileField(default='https://back.dcubamusica.cult.cu/public/images/blank.webp', null=True, upload_to='images/')),
                ('cargo', models.CharField(max_length=100)),
                ('télefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('consejo_de_dirección', models.BooleanField()),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entidades.centros_y_empresas')),
            ],
            options={
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='BannerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenedor', models.CharField(choices=[('ContenedorConFondo', 'Tipo 1'), ('ContenedorConFondoSoloTitulo', 'Tipo 2'), ('ContenedorICM', 'Contenedor: Tipo 3'), ('Evento', 'Contenedor: Evento'), ('Acontecimiento', 'Contenedor: Acontecimiento'), ('Efemeride', 'Contenedor: Efemeride')], max_length=50)),
                ('titulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('encabezado', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('foto', models.FileField(null=True, upload_to='images/')),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], max_length=7, null=True)),
                ('numero_unico', models.PositiveIntegerField(unique=True)),
                ('seleccionar_acontecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_principal', to='entidades.acontecimiento')),
                ('seleccionar_efemeride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_principal', to='entidades.efemerides')),
                ('seleccionar_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_principal', to='entidades.evento')),
            ],
            options={
                'verbose_name_plural': 'Banner Principal',
            },
        ),
    ]
