# Generated by Django 5.0.1 on 2024-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenedorConFondo',
        ),
        migrations.DeleteModel(
            name='ContenedorConFondoSoloTitulo',
        ),
        migrations.DeleteModel(
            name='ContenedorICM',
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
