# Generated by Django 5.0.1 on 2024-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerprincipal',
            name='tipo_contenedor',
            field=models.CharField(choices=[('ContenedorConFondo', 'Tipo 1'), ('ContenedorConFondoSoloTitulo', 'Tipo 2'), ('ContenedorICM', 'Tipo 3'), ('Evento', 'Contenedor: Evento'), ('Acontecimiento', 'Contenedor: Acontecimiento'), ('Efemeride', 'Contenedor: Efemeride')], max_length=50),
        ),
    ]
