# Generated by Django 5.0.1 on 2024-05-08 03:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_remove_acontecimiento_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premio_nacional_de_música',
            old_name='bibliografía',
            new_name='bibliografía_en',
        ),
        migrations.AddField(
            model_name='premio_nacional_de_música',
            name='bibliografía_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
