# Generated by Django 5.0.1 on 2024-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_premio_nacional_de_música_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='archivo_local',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='link_podcast',
            field=models.URLField(blank=True, null=True),
        ),
    ]
