# Generated by Django 5.0.1 on 2024-02-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_bannerprincipal_numero_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='numero_unico',
        ),
    ]
