# Generated by Django 5.0.1 on 2024-05-08 05:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_rename_bibliografía_premio_nacional_de_música_bibliografía_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(default='a'),
        ),
        migrations.AddField(
            model_name='revista',
            name='titulo_en',
            field=ckeditor.fields.RichTextField(default='a'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='encabezado_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='encabezado_es',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='titulo_es',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='efemerides',
            name='foto',
            field=models.FileField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='historia_de_la_institución',
            name='foto',
            field=models.FileField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(upload_to='multimedias/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='enlace',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='foto',
            field=models.FileField(max_length=500, upload_to='multimedias/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='link_podcast',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='titulo_es',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='premio_nacional_de_música',
            name='bibliografía_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='premio_nacional_de_música',
            name='bibliografía_es',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='premio_nacional_de_música',
            name='foto',
            field=models.FileField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='redes',
            name='enlace',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='redes',
            name='foto',
            field=models.FileField(max_length=500, upload_to='redes/'),
        ),
    ]
