# Generated by Django 5.0.1 on 2024-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_revista_descripcion_en_revista_titulo_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerprincipal',
            name='foto',
            field=models.FileField(default='#ffffff', max_length=500, null=True, upload_to='images/'),
        ),
    ]
