# Generated by Django 5.0.1 on 2024-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_podcast_archivo_local_alter_podcast_link_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='archivo_local',
            field=models.FileField(blank=True, null=True, upload_to='podcast/'),
        ),
    ]
