# Generated by Django 5.0.1 on 2024-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_alter_bannerprincipal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerprincipal',
            name='color_de_fondo',
            field=models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], default='#ffffff', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='foto',
            field=models.FileField(max_length=500, null=True, upload_to='images/'),
        ),
    ]
