# Generated by Django 5.0.1 on 2024-02-06 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_bannerprincipal_numero_unico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion_Efemerides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_de_fondo', models.CharField(choices=[('#000000', 'negro'), ('#ffffff', 'blanco'), ('#4f4f4f', 'gris'), ('#29385c', 'azul'), ('36454d', 'verde'), ('0d032b', 'malva'), ('ed8500', 'naranja')], max_length=7, null=True)),
                ('numero_unico', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('seleccionar_efemeride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seccion_efemerides', to='entidades.efemerides')),
            ],
        ),
    ]
