# Generated by Django 5.0.1 on 2024-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_alter_podcast_archivo_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='fecha',
            field=models.DateField(default='2002-11-11'),
        ),
    ]
