# Generated by Django 5.0.1 on 2024-05-19 03:50

import apps.entidades.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_alter_bannerprincipal_color_de_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerprincipal',
            name='foto',
            field=models.FileField(max_length=500, null=True, storage=apps.entidades.storage.CustomStorage(), upload_to='images/'),
        ),
    ]
