# Generated by Django 5.0.1 on 2024-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_revista_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='fecha',
            field=models.DateField(),
        ),
    ]
