# Generated by Django 5.0.1 on 2024-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_iconos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('link_podcast', models.URLField(max_length=1024)),
                ('foto', models.ImageField(upload_to='fotos_podcast/')),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('imagen_portada', models.ImageField(upload_to='portadas/')),
            ],
        ),
        migrations.AlterField(
            model_name='iconos',
            name='foto',
            field=models.FileField(max_length=1000, null=True, upload_to='logos/'),
        ),
    ]
