# Generated by Django 5.0.1 on 2024-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0008_podcast_revista_alter_iconos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='imagen_portada',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
