# Generated by Django 5.0.1 on 2024-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_alter_revista_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='es_ceo',
            field=models.BooleanField(default=False, verbose_name='¿Es CEO?'),
        ),
        migrations.AddField(
            model_name='directores',
            name='es_cto',
            field=models.BooleanField(default=False, verbose_name='¿Es CTO?'),
        ),
        migrations.AlterField(
            model_name='directores',
            name='consejo_de_dirección',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directores',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='directores',
            name='foto',
            field=models.FileField(default='images/blank.webp', null=True, upload_to='images/'),
        ),
    ]
