# Generated by Django 5.0.1 on 2024-04-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0010_directores_es_ceo_directores_es_cto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='multimedias/'),
        ),
        migrations.AlterField(
            model_name='directores',
            name='consejo_de_dirección',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='directores',
            name='foto',
            field=models.FileField(blank=True, default='images/blank.webp', null=True, upload_to='images/'),
        ),
    ]
