# Generated by Django 5.0.1 on 2024-04-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_multimedia_archivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
