# Generated by Django 5.0.1 on 2024-04-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_rename_nombre_multimedia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='multimedias/'),
        ),
    ]
