# Generated by Django 5.0.1 on 2024-04-28 22:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0013_alter_multimedia_enlace_alter_multimedia_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', ckeditor.fields.RichTextField()),
                ('enlace', models.URLField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='redes/')),
            ],
            options={
                'verbose_name_plural': 'Redes',
            },
        ),
    ]
