# Generated by Django 5.0.1 on 2024-04-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0014_redes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redes',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
