# Generated by Django 5.0.1 on 2024-04-29 02:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0015_rename_nombre_redes_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='titulo_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='titulo_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
