# Generated by Django 5.0.1 on 2024-04-29 02:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0016_podcast_descripcion_en_podcast_descripcion_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='titulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='titulo_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='titulo_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
