# Generated by Django 5.0.1 on 2024-05-03 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0020_acontecimiento_descripcion_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='descripcion_en',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='descripcion_es',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='encabezado_en',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='encabezado_es',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='titulo_en',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='titulo_es',
        ),
    ]
