# Generated by Django 5.0.1 on 2024-05-03 03:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0021_remove_bannerprincipal_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerprincipal',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='encabezado_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='encabezado_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='titulo_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='titulo_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
