# Generated by Django 5.0.1 on 2024-05-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0022_bannerprincipal_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='imagen_portada',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='pdf',
            field=models.FileField(max_length=500, upload_to='pdfs/'),
        ),
    ]
