# Generated by Django 5.0.1 on 2024-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0023_alter_revista_imagen_portada_alter_revista_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='archivo_local',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='podcast/'),
        ),
    ]
