# Generated by Django 5.0.1 on 2024-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0024_alter_podcast_archivo_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='archivo_local',
            field=models.FileField(max_length=500, upload_to='podcast/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
