# Generated by Django 5.0.1 on 2024-05-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0025_alter_podcast_archivo_local_alter_podcast_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='foto',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
    ]
