# Generated by Django 5.0.1 on 2024-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0026_alter_podcast_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acontecimiento',
            name='foto',
            field=models.FileField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='foto',
            field=models.FileField(max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='centros_y_empresas',
            name='correo',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='directores',
            name='cargo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='directores',
            name='cargo_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='directores',
            name='cargo_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='efemerides',
            name='foto',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.FileField(max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='historia_de_la_institución',
            name='foto',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='iconos',
            name='foto',
            field=models.FileField(max_length=500, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='foto',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='multimedias/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tipo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='premio_nacional_de_música',
            name='foto',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='redes',
            name='foto',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='redes/'),
        ),
    ]
