# Generated by Django 5.0.1 on 2024-05-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0028_alter_directores_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='foto',
            field=models.FileField(blank=True, default='blank.webp', null=True, upload_to='images/'),
        ),
    ]
