
BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXX XX XXX XXXXXXXXXX XXXXXX X XXXXXXXXXXXXXX
                            XXXXXXXX
                        XXXXXX
                    XXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
